"""Migración inicial limpia

Revision ID: 00662891ce80
Revises: 
Create Date: 2026-06-18 19:22:39.924279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00662891ce80'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('idCategoria', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('idCategoria')
    )
    op.create_table('roles',
    sa.Column('idRol', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('idRol'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('prenda',
    sa.Column('idPrenda', sa.Integer(), nullable=False),
    sa.Column('idCategoria', sa.Integer(), nullable=False),
    sa.Column('nombre_prenda', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('talla', sa.String(length=10), nullable=False),
    sa.Column('color', sa.String(length=30), nullable=False),
    sa.Column('precio_alquiler', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['idCategoria'], ['categoria.idCategoria'], ),
    sa.PrimaryKeyConstraint('idPrenda')
    )
    op.create_table('usuarios',
    sa.Column('idUsuario', sa.Integer(), nullable=False),
    sa.Column('idRol', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('documento', sa.String(length=20), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('correo', sa.String(length=100), nullable=False),
    sa.Column('contrasena', sa.String(length=255), nullable=False),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['idRol'], ['roles.idRol'], ),
    sa.PrimaryKeyConstraint('idUsuario'),
    sa.UniqueConstraint('correo'),
    sa.UniqueConstraint('documento')
    )
    op.create_table('inventario',
    sa.Column('idInventario', sa.Integer(), nullable=False),
    sa.Column('idPrenda', sa.Integer(), nullable=False),
    sa.Column('codigo_interno', sa.String(length=30), nullable=False),
    sa.Column('estado', sa.Enum('DISPONIBLE', 'ALQUILADO', 'MANTENIMIENTO', name='estadoinventario'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['idPrenda'], ['prenda.idPrenda'], ),
    sa.PrimaryKeyConstraint('idInventario'),
    sa.UniqueConstraint('codigo_interno')
    )
    op.create_table('reserva',
    sa.Column('idReserva', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('id_administrador', sa.Integer(), nullable=False),
    sa.Column('fecha_reserva', sa.Date(), server_default=sa.text('(CURRENT_DATE)'), nullable=False),
    sa.Column('fecha_evento', sa.Date(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('fecha_devolucion', sa.Date(), nullable=True),
    sa.Column('estado', sa.Enum('PENDIENTE', 'ENTREGADO', 'DEVUELTO', 'CANCELADO', name='estadoreserva'), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_administrador'], ['usuarios.idUsuario'], ),
    sa.ForeignKeyConstraint(['id_cliente'], ['usuarios.idUsuario'], ),
    sa.PrimaryKeyConstraint('idReserva')
    )
    op.create_table('cita',
    sa.Column('idCita', sa.Integer(), nullable=False),
    sa.Column('id_administrador', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('id_reserva', sa.Integer(), nullable=True),
    sa.Column('fecha_cita', sa.DateTime(), nullable=False),
    sa.Column('motivo', sa.String(length=150), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_administrador'], ['usuarios.idUsuario'], ),
    sa.ForeignKeyConstraint(['id_cliente'], ['usuarios.idUsuario'], ),
    sa.ForeignKeyConstraint(['id_reserva'], ['reserva.idReserva'], ),
    sa.PrimaryKeyConstraint('idCita')
    )
    op.create_table('comprobante',
    sa.Column('idComprobante', sa.Integer(), nullable=False),
    sa.Column('idReserva', sa.Integer(), nullable=False),
    sa.Column('numero_comprobante', sa.String(length=30), nullable=False),
    sa.Column('tipo_comprobante', sa.String(length=30), nullable=False),
    sa.Column('monto_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['idReserva'], ['reserva.idReserva'], ),
    sa.PrimaryKeyConstraint('idComprobante'),
    sa.UniqueConstraint('numero_comprobante')
    )
    op.create_table('detalle_reserva',
    sa.Column('idDetalle_Reserva', sa.Integer(), nullable=False),
    sa.Column('idReserva', sa.Integer(), nullable=False),
    sa.Column('idInventario', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['idInventario'], ['inventario.idInventario'], ),
    sa.ForeignKeyConstraint(['idReserva'], ['reserva.idReserva'], ),
    sa.PrimaryKeyConstraint('idDetalle_Reserva')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detalle_reserva')
    op.drop_table('comprobante')
    op.drop_table('cita')
    op.drop_table('reserva')
    op.drop_table('inventario')
    op.drop_table('usuarios')
    op.drop_table('prenda')
    op.drop_table('roles')
    op.drop_table('categoria')
    # ### end Alembic commands ###
